language: node_js
node_js:
  - lts/*

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

cache:
  directories:
    - ~/.yarn-cache
    - node_modules
    - www/node_modules

addons:
  chrome: stable
  firefox: latest

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - yarn bootstrap

after_success:
  - node_modules/.bin/codecov
after_success:
  - if ([ ! -z "$TRAVIS_TAG" ]); then
    yarn build-docs
  fi
  - yarn codecov

branches:
  only:
    - master

deploy:
  provider: pages
  repo: react-bootstrap/react-bootstrap.github.io
  local-dir: www/public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    tags: true
